language: java
jdk:
- oraclejdk8
script:
- mvn verify -DhawkularUrl="${HAWKULAR_ENDPOINT}" -DauthenticationKey="${SAUCELABS_AUTH_KEY}"
env:
  global:
    secure: d31XYDmy+/Tmo+HcdExxypC7m2R8iM4tyPnRqgGmxzGuuq2iOotxXnV8ShM/PsWxN4tcVk0r9fyoRIUfllFUl+JsgER41PeDJHIq0KqhkVI18wZXv2OrhWU4HkrgT92U6D5oWjYBclo7jMf4CS2BM7GQKsBhjRvWpp2one6l6+qKoNDWArgpmbizHl6PTPpq5CG7mSxqzjymLOwSOfdPgUN+bBlDYOFArYmLh6R1PrSz8l7iWl/ysBzpiAq20O/WkZ09kojxbJP2hhjcMTuL9Uzu8KIDX+YPYyml8O3FZwgs+Y/N7L1b3DXf12X7NUvJhYlnKZvJ95lLm84cfxfTErx5ep+X0PVjAZD5FpUEW1AwFadXgzGKxz2xskUDdtJ8FkYv06RUebmB4mM+ZaPnE0aSnbC4fGLssDLCMynZYP1zjs7TPG3wO46kUdwmY8C+WvHeip7pnLgHYhnlEHtPFJ9a1P3mzk/PnCc/QFvb6CBs/y6B+BEDKKqqfMJNNeHF5h7fe0qIiEQHy2BJ2SihaXAB/zBubjumJ3+4ykKlG8Hfl6feaesHeb60upVF9a1l8U7XlGz2alCEFqeszoQnOJRs5Fczb3zd7LzMQF/k6l26BaAsABVs6vq+qlRo+dNrOMfAWdBofVV4Twb2Y4ECQKT7xA0wEsd30OrHz3SeFn8=
